---
collections:
  posts:
    output: true
    permalink: "/:categories/:year/:month/:day/:title:output_ext"
exclude:
- README.md
- vendor
show_drafts: 
port: 4000
timezone: 
title: Jekyll Starter Theme
subtitle: Another Minimalistic Static Site Quick Starter Theme
path: "/jekyll-starter-theme"
url: http://henrythemes.github.io/jekyll-starter-theme
